#!/usr/bin/env python3
import os, subprocess, sys
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    met = subprocess.check_output(['zenity', '--forms', '--add-entry=artist', '--add-entry=title', f'--text={file}']).decode("utf-8")
    met = met.split('|')
    met[0] = met[0].strip("\\n")
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, "-c", "copy", "-metadata", f"artist={met[0].replace('\n', '')}", "-metadata", f"title={met[1].replace('\n', '')}", "tmp.mp3"])
    ffm.wait()
    mvs = subprocess.Popen(["mv", "-f", "tmp.mp3", file])
    mvs.wait()
