#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
scale = subprocess.check_output(["zenity", "--entry", "--text=Scale", "--entry-text=1920x1080"]).decode("UTF-8").replace('\n','')

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    subprocess.Popen(["magick", file, "-resize", scale, f"{f}_scaled{ext}"]).wait()
