#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    subprocess.Popen(["magick", f"{f}{ext}", "-gravity", "west", '-crop', "%hx%h+0+0", f"{file}_sqr{ext}"])
