#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
	ffp = subprocess.Popen(["kitty","ffmpeg", "-i", file, "-b", "12k", "-b:a", "12k", f"{f}_12k.mp4"])
	ffp.wait()
