#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
	ffp = subprocess.Popen(["ffmpeg", "-i", file, "-b", "48k", "-b:a", "48k", f"{file}_48k.mp4"])
	ffp.wait()
