#!/bin/bash
tgpt -q  "napisz streszczenie $(cat "$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")")" &> /home/wilwe/Dokumenty/aiout
notify-send "koniec chuju" -a "Ai chuj"
playerctl pause
spd-say -w "$(cat '/home/wilwe/Dokumenty/aiout')"
playerctl play
