#!/bin/bash
tgpt -q  "Zamień każdą osobę i zaimki słowem 'Gryzak' w tym tekście $(cat "$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")")" &> $HOME/Dokumenty/aiout
playerctl pause
spd-say -l pl -w "$(cat '/home/wilwe/Dokumenty/aiout')"
playerctl play
