#!/bin/bash
tgpt -q  "Zamień każdą osobę i zaimki słowem GRYZAK "$(cat "$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")")"" &> $HOME/Dokumenty/aiout
notify-send "koniec chuju" -a "Ai chuj"
playerctl pause
spd-say -w "$(cat '/home/wilwe/Dokumenty/aiout')"
playerctl play
