#!/bin/bash
x=$(tgpt -q  "Zamień każdą osobę i zaimki słowem 'GRYZAK' "$(cat "$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")")"")
echo "${x//GRYZAK/nigger}" > $HOME/Dokumenty/aiout
notify-send "koniec chuju" -a "Ai chuj"
playerctl pause
spd-say -w "$(cat "$HOME/Dokumenty/aiout")"
playerctl play
