#!/bin/bash
x=$(tgpt -q  "Zamień każdą osobę i zaimki słowem 'Gryzak' w tym tekście $(cat "$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")")")
echo "${x//Gryzak/nigger}" > $HOME/Dokumenty/aiout
playerctl pause
spd-say -l pl -w "$(cat "$HOME/Dokumenty/aiout")"
playerctl play
