#!/bin/bash
tgpt -q  "połącz teksty aby były spójne ze sobą $(cat $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)" &> /home/wilwe/Dokumenty/aiout
playerctl pause
spd-say -l pl -w "$(cat '/home/wilwe/Dokumenty/aiout')"
playerctl play
