#!/usr/bin/env python3
import os, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-l", "--language", help="Specyfy language", default="pl")
parser.add_argument("-v", "--voice", help="Speak answer", action=argparse.BooleanOptionalAction)
args = parser.parse_args()
while 0 == 0:
    print("\x1b[38;2;203;166;247m\x1b[0m\x1b[48;2;203;166;247m\x1b[38;2;24;24;37mYou\x1b[0m\x1b[38;2;203;166;247m\x1b[0m")
    try:
        a = input().replace('"', '').replace("'", "").replace("`","")
    except:
        break
    if a in ['exit',':q']:
        break
    print("")
    if args.language != None and args.language.lower() != "enchant" and args.language.lower() != "braill" and args.language.lower() != "illuminati" and args.language.lower() != "morse" and args.language.lower() != "spc":
        a = os.popen(f"tpl -l {args.language} -s {a}").read()
        b = os.popen(f"tgpt -q '{a}'").read().replace("(","").replace(")","").strip('\n')
    if args.language != None and args.language.lower() == "enchant":
        print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mEnchanting Table\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
        a = os.popen(f"tpl -l en -s {a}").read()
        b = os.popen(f"tgpt -q '{a}'").read().replace("(","").replace(")","").strip('\n')
        b = b.replace("'","")
        print(os.popen(f"enchant -s '{b}'").read())
        print("")
        print("\x1b[91;1m———————————————————————\x1b[0m")
        print("")
    elif args.language != None and args.language.lower() == "braill":
        print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37m⠁⠊\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
        b = os.popen(f"tgpt -q '{a}'").read().replace("(","").replace(")","").strip('\n')
        b = b.replace("'","")
        print(os.popen(f"braill -s '{b}'").read())
        print("")
        print("\x1b[91;1m———————————————————————\x1b[0m")
        print("")
    elif args.language != None and args.language.lower() == "illuminati":
        print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mIlluminaci\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
        a = os.popen(f"tpl -l en -s {a}").read()
        b = os.popen(f"tgpt -q '{a}'").read().replace("(","").replace(")","").strip('\n')
        b = b.replace("'","")
        print(os.popen(f"illuminati -s '{b}'").read())
        print("")
        print("\x1b[91;1m———————————————————————\x1b[0m")
        print("")
    elif args.language != None and args.language.lower() == "morse":
        print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mMorsy\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
        b = os.popen(f"tgpt -q '{a}'").read().replace("(","").replace(")","").strip('\n')
        b = b.replace("'","")
        print(os.popen(f"morse -s '{b}'").read())
        print("")
        print("\x1b[91;1m———————————————————————\x1b[0m")
        print("")
    elif args.language != None and args.language.lower() == "spc":
        print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mSpc\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
        b = os.popen(f"tgpt -q '{a}'").read().replace("(","").replace(")","").strip('\n')
        b = b.replace("'","¾")
        print(os.popen(f"spc -s '{b}'").read().replace("¾","'0"))
        print("")
        print("\x1b[91;1m———————————————————————\x1b[0m")
        print("")
    else:
        print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mAI\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
        print(str(b))
        if args.voice != None:
            b = b.replace('"',"")
            os.popen(f'tts -m -l {args.language} -s "{b}"')
        print("")
        print("\x1b[91;1m———————————————————————\x1b[0m")
        print("")
