#!/usr/bin/env python3
import os, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-l", "--language", help="Specyfy language", default="pl")
args = parser.parse_args()
while 0 == 0:
    print("\033[38;2;203;166;247m🭃\033[0m\033[48;2;203;166;247m\033[38;2;24;24;37mYou\033[0m\033[38;2;203;166;247m🭟\033[0m")
    a = input().replace('"', '')
    print("")
    print("\033[91;1m-----------------------\033[0m")
    print("")
    if args.language != None and args.language.lower() != "enchant" and args.language.lower() != "braill":
        a = os.popen(f"trans -t {args.language} -j -brief -show-original n -show-translation Y -show-original-phonetics n -show-translation-phonetics n -show-languages n -show-dictionary n -show-alternatives n -no-ansi -no-autocorrect {a}").read()
        b = os.popen(f'tgpt -q "{a}"').read().replace("(","").replace(")","").strip('\n')
    if args.language != None and args.language.lower() == "enchant":
        print("\033[38;2;166;227;161m🭃\033[0m\033[48;2;166;227;161m\033[38;2;24;24;37mEnchanting Table\033[0m\033[38;2;166;227;161m🭟\033[0m")
        a = os.popen(f"trans -t en -j -brief -show-original n -show-translation Y -show-original-phonetics n -show-translation-phonetics n -show-languages n -show-dictionary n -show-alternatives n -no-ansi -no-autocorrect {a}").read()
        b = os.popen(f'tgpt -q "{a}"').read().replace("(","").replace(")","").strip('\n')
        b = b.replace("'","")
        print(os.popen(f"enchant -s '{b}'").read())
    elif args.language != None and args.language.lower() == "braill":
        print("\033[38;2;166;227;161m🭃\033[0m\033[48;2;166;227;161m\033[38;2;24;24;37m⠁⠊\033[0m\033[38;2;166;227;161m🭟\033[0m")
        b = os.popen(f'tgpt -q "{a}"').read().replace("(","").replace(")","").strip('\n')
        b = b.replace("'","")
        print(os.popen(f"braill -s '{b}'").read())
    else:
        print("\033[38;2;166;227;161m🭃\033[0m\033[48;2;166;227;161m\033[38;2;24;24;37mAI\033[0m\033[38;2;166;227;161m🭟\033[0m")
        print(str(b))
        b = b.replace('"',"")
        os.popen(f'tts -m -l {args.language} -s "{b}"')
        print("\033[91;1m-----------------------\033[0m")
        print("")
