#!/usr/bin/env python3
import os, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-l", "--language", help="Specyfy language", default="pl")
args = parser.parse_args()
while 0 == 0:
    print("\033[38;2;203;166;247m🭃\033[0m\033[48;2;203;166;247m\033[38;2;24;24;37mTy:\033[0m\033[38;2;203;166;247m🭟\033[0m")
    a = input().replace('"', '')
    print("")
    print("\033[91;1m-----------------------\033[0m")
    print("")
    b = os.popen(f'tgpt -q "{a}"').read()
    print("\033[38;2;236;234;121m🭃\033[0m\033[48;2;236;234;121m\033[38;2;24;24;37mAI:\033[0m\033[38;2;236;234;121m🭟\033[0m")
    print(str(b))
    b = b.replace('"', '')
    os.popen(f'tts -m -l {args.language} -s "{b}"')
    print("\033[91;1m-----------------------\033[0m")
    print("")
