#!/usr/bin/env python3
import random
yes = ['yes', 'y','', 'tak', 't']
symbols = ['󱀝', '♡', '󰣎', '󰣑']
cards = ["2","3","4","5","6","7","8","9","1","J","Q","K","A"]
W = 0
L = 0
class Char:
    def __init__(self):
        self.asc = 0
        self.hand = [cards[random.randint(0,12)], cards[random.randint(0,12)]]
        self.hands = [symbols[random.randint(0,3)]]
        self.get_symbol()
        self.value = 0
    def as_update(self):
        while self.value > 21 and self.asc > 0:
            self.value -= 9
            self.asc -= 1
    def count_val(self):
        self.value = 0
        for i in self.hand:
            if i == "1":
                self.value += 10
            elif i.isnumeric():
                self.value += int(i)
            elif i == "J":
                self.value += 10
            elif i == "Q":
                self.value += 10
            elif i == "K":
                self.value += 10
            elif i == "A":
                self.asc += 1
                self.value += 10
            self.as_update()
    def get_card(self):
        DRAW = cards[random.randint(0,12)]
        DRAWS = symbols[random.randint(0,3)]
        if DRAW in self.hand:
            if DRAWS in self.hands[self.hand.index(DRAW)]:
                self.get_card()
            else:
                self.get_card()
        else:
            self.hand += [DRAW]
            self.hands += [DRAWS]
    def get_hand(self):
        handr = []
        handc = ""
        for i in self.hand:
            if i == "1":
                handr += ["10"]
            else:
                handr += [i]
        for i in range(len(handr)):
            handc = f"{handc} {handr[i]}{self.hands[i]}"
        return handc
    def get_symbol(self):
        DRAWS = symbols[random.randint(0,3)]
        if self.hand[0] == self.hand[1]:
            if DRAWS in self.hands:
                self.get_symbol()
            else:
                self.hands += [DRAWS]
        else:
            self.hands += [DRAWS]
run = True
def main():
    global W, L
    player = Char()
    enemy = Char()
    while 0 == 0:
        player.count_val()
        handc = player.get_hand()
        enemy.count_val()
        Ehandc = enemy.get_hand()
        print("\033cEnemy:"+Ehandc)
        print(enemy.value)
        print("you:"+handc)
        print(player.value)
        print(f"hit/stand {str(W)}/{str(L)}")
        try:
            a = input("").lower()
        except:
            break
        match a:
            case "hit":
                player.get_card()
                player.count_val()
                handc = player.get_hand()
                print("\033cEnemy:"+Ehandc)
                print(enemy.value)
                print("you:"+handc)
                print(player.value)
                if player.value > 21:
                    L += 1
                    print(f"Przegrałeś {str(W)}/{str(L)}")
                    break
                else:
                    continue
            case "stand":
                if player.value == 21:
                    W += 1
                    print(f"Wygrałeś {str(W)}/{str(L)}")
                else:
                    enemy.get_card()
                    enemy.count_val()
                    Ehandc = enemy.get_hand()
                    print("\033cEnemy:"+Ehandc)
                    print(enemy.value)
                    print("you:"+handc)
                    print(player.value)
                    while enemy.value <19:
                        enemy.get_card()
                        enemy.count_val()
                        Ehandc = enemy.get_hand()
                        print("\033cEnemy:"+Ehandc)
                        print(enemy.value)
                        print("you:"+handc)
                        print(player.value)
                    if enemy.value > 21:
                        W += 1
                        print(f'Wygrałeś {str(W)}/{str(L)}')
                    elif enemy.value > player.value:
                        L += 1
                        print(f"Przegrałeś {str(W)}/{str(L)}")
                    else:
                        W += 1
                        print(f"Wygrałeś {str(W)}/{str(L)}")
                break
            case "exit":
                run = False
                break
            case _:
                pass
main()
while run:
    print("Play Again?")
    try:
        g = input("")
    except:
        break
    if g in yes:
        main()
    else:
        break
