#!/usr/bin/env python3
import os, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-b", "--braill", help="From braill?", action=argparse.BooleanOptionalAction)
parser.add_argument("-s", "--single", help="single", nargs="*")
args = parser.parse_args()
brail = {"a": "⠁","b": "⠃","c": "⠉","d": "⠙","e": "⠑","f": "⠋","g": "⠛","h": "⠓","i": "⠊","j": "⠚","k": "⠅","l": "⠇","m": "⠍","n": "⠝","o": "⠕","p": "⠏","q": "⠟","r": "⠗","s": "⠎","t": "⠞","u": "⠥","v": "⠧","w": "⠺","x": "⠭","y": "⠽","z": "⠵","ą":"⠡","ć":"⠩","ę":"⠱","ł":"⠣","ń":"⠹","ó":"⠬","ś":"⠪","ż":"⠯","ź":"⠮","0":"⠼⠚","1":"⠼⠁","2":"⠼⠃","3":"⠼⠉","4":"⠼⠙","5":"⠼⠑","6":"⠼⠋","7":"⠼⠛","8":"⠼⠓","9":"⠼⠊"}
normal = {"⠁":"a","⠃":"b","⠉":"c","⠙":"d","⠑":"e","⠋":"f","⠛":"g","⠓":"h","⠊":"i","⠚":"j","⠅":"k","⠇":"l","⠍":"m","⠝":"n","⠕":"o","⠏":"p","⠟":"q","⠗":"r","⠎":"s","⠞":"t","⠥":"u","⠧":"v","⠺":"w","⠭":"x","⠽":"y","⠵":"z","⠡":"ą","⠩":"ć","⠱":"ę","⠣":"ł","⠹":"ń","⠬":"ó","⠪":"ś","⠯":"ż","⠮":"ź"}

while not args.braill and args.single == None:
    print("\033[38;2;203;166;247m\033[0m\033[48;2;203;166;247m\033[38;2;24;24;37mYou\033[0m\033[38;2;203;166;247m\033[0m")
    try:
        a = input().replace('"', '').lower()
    except:
        break
    if a in ["exit",":q"]:
        break
    print("")
    print("\033[38;2;166;227;161m\033[0m\033[48;2;166;227;161m\033[38;2;24;24;37m⠃⠗⠁⠊⠇⠇\033[0m\033[38;2;166;227;161m\033[0m")
    print(''.join(brail.get(ch,ch) for ch in a))
    print("")
    print("\033[91;1m———————————————————————\033[0m")
    print("")
while args.braill and args.single == None:
    print("\033[38;2;203;166;247m\033[0m\033[48;2;203;166;247m\033[38;2;24;24;37m⠽⠕⠥\033[0m\033[38;2;203;166;247m\033[0m")
    try:
        a = input().replace('"', '').lower()
    except:
        break
    if a in ["exit",":q"]:
        break
    print("")
    print("\033[38;2;166;227;161m\033[0m\033[48;2;166;227;161m\033[38;2;24;24;37mBraill\033[0m\033[38;2;166;227;161m\033[0m")
    a = a.replace("⠼⠚", "0").replace("⠼⠁", "1").replace("⠼⠃", "2").replace("⠼⠉", "3").replace("⠼⠙", "4").replace("⠼⠑", "5").replace("⠼⠋", "6").replace("⠼⠛", "7").replace("⠼⠓", "8").replace("⠼⠊", "9")
    print(''.join(normal.get(ch,ch) for ch in a))
    print("")
    print("\033[91;1m———————————————————————\033[0m")
    print("")
if args.single != None:
    if not args.braill:
        print(''.join(brail.get(ch,ch) for ch in ' '.join(args.single).lower()))
    elif args.braill:
        a = ' '.join(args.single).lower().replace("⠼⠚", "0").replace("⠼⠁", "1").replace("⠼⠃", "2").replace("⠼⠉", "3").replace("⠼⠙", "4").replace("⠼⠑", "5").replace("⠼⠋", "6").replace("⠼⠛", "7").replace("⠼⠓", "8").replace("⠼⠊", "9")
        print(''.join(normal.get(ch,ch) for ch in a))
