#!/usr/bin/env python3
import time
class character:
    def __init__(self, health, power):
        self.health = health
        self.power = power
    def takedmg(self, value):
        self.health -= value
print("\033c")
stachu = character(20,2)
i = input("What's up dog?")
if i == "yo gut":
    print("Nice cock")
else:
    print("This means fight")
    battle = True
    while battle:
        print(f"You: {stachu.health}")
        print("Carlos: 20")
        time.sleep(1)
        stachu.takedmg(2)
        print("\033c")
