#!/usr/bin/env python3
import random, sys, os, argparse, requests, yaml, subprocess, time
parser = argparse.ArgumentParser()
parser.add_argument("-m", "--message", help="Set message", nargs="*")
parser.add_argument("-m2", "--message2", help="Set message2", nargs="*")
parser.add_argument("-c", "--channel", help="Set channel")
parser.add_argument("-mi", "--messageid", help="Set messageid")
args = parser.parse_args()
with open("/home/wilwe/.config/lyr.yaml", encoding='utf-8', errors='ignore') as f:
    data = yaml.safe_load(f)
token = data['token']
channel = data['channel']
if args.channel != None:
    channel = args.channel
def sendMessage(message):
    url = f'https://discord.com/api/v9/channels/{channel}/messages/{args.messageid}'
    payload = {
        "content": message
    }

    headers = {
        "Authorization": token
    }
    res = requests.patch(url, payload, headers=headers)
if __name__ == '__main__':
    message = ''.join(args.message)
    message2 = ''.join(args.message2)
    while True:
        sendMessage(message)
        print(message)
        time.sleep(5)
        sendMessage(message2)
        print(message2)
        time.sleep(5)
