#!/usr/bin/env python3
import random, sys, os, argparse, requests, yaml, subprocess
parser = argparse.ArgumentParser()
parser.add_argument("-m", "--message", help="Set message", nargs="*")
parser.add_argument("-c", "--channel", help="Set channel")
args = parser.parse_args()
with open("/home/wilwe/.config/lyr.yaml", encoding='utf-8', errors='ignore') as f:
    data = yaml.safe_load(f)
token = data['token']
channel = data['channel']
if args.channel != None:
    channel = args.channel
def sendMessage(message):
    url = f'https://discord.com/api/v9/channels/{channel}/messages'
    payload = {
        "content": message
    }

    headers = {
        "Authorization": token
    }
    res = requests.post(url, payload, headers=headers)
if __name__ == '__main__':
    message = ''.join(args.message)
    if len(message) > 2000:
        chunks = []
        start = 0
        end = 2000
        while start < len(message):
            chunk = message[start:end]
            chunks.append(chunk)
            start = end
            print(f"start: {start}")
            end += 2000
            print(f"end: {end}")
        for chunk in chunks:
            sendMessage(chunk)
    else:
        sendMessage(message)
