#!/usr/bin/env python3
import math
class funkcja():
    def __init__(self,nonx,x):
        self.x = x
        self.a = nonx
    def print(self):
        end = ""
        ar = {}
        for num, i in enumerate(self.x):
            if i != 0:
                ar[num] = i
        for key, value in ar.items():
            end += f"+{value}x{key+1 if key+1 > 1 else ''}"
        if self.a != "":
            end+= f"+{self.a}"
        return end
    def delta(self):
        calc = self.x[0]**2-4*self.x[1]*self.a
        if calc >= 0:
            return calc
        else:
            raise ValueError("Delta ujemna")
    def pierwiastek(self):
        try:
            pierdel = math.sqrt(self.delta())
        except:
            pierdel = "ujemna wyszła"
        return pierdel
    def miejsca0(self):
        delta = self.delta()
        if delta < 0:
            return []
        else:
            xy = []
            xy.append((-1*self.x[0]+delta)/(2*self.x[1]))
            xy.append((-1*self.x[0]-delta)/(2*self.x[1]))
        return xy
    def new(liczba):
        end = []
        st = ""
        for i in liczba:
            if liczba[0] == i:
                st += i
            elif i == "+":
                end.append(st)
                st = ""
            elif i == "-":
                end.append(st)
                st = i
            else:
                st += i
        if end[-1] != st:
            end.append(st)
        nonx = []
        x = [[] for _ in range(10000)]
        for i in end:
            cur = ""
            sas = ""
            for j in i:
                if j == "x":
                    cur += j
                elif cur == "x":
                    sas += j
            if cur == "":
                nonx.append(i)
            else:
                try:
                    x[int(sas)-1].append(i)
                except:
                    x[0].append(i)
        ennonx = [int(i) for i in nonx]
        a = sum(ennonx)
        enx = [sum([int(j.replace(f"x{en+1 if en+1 > 1 else ''}", "")) for j in i]) for en, i in enumerate(x)]
        return funkcja(a, enx)

if __name__ == "__main__":
    print("Daj funkcje chuju: ")
    a = input()
    fun = funkcja.new(a)
    print(fun.print())
    print(fun.pierwiastek())

