#!/usr/bin/env python3
import math, numpy
class funkcja():
    def __init__(self,nonx,x):
        self.x = x
        self.a = nonx
        self.sol = set()
        self.miejsca0()
    def print(self):
        end = ""
        ar = {}
        for num, i in enumerate(self.x):
            if i != 0:
                ar[num] = i
        for key, value in ar.items():
            end += f"+{value}x{key+1 if key+1 > 1 else ''}"
        if self.a != "":
            end+= f"+{self.a}"
        return end
    def delta(self):
        if sum(self.x[2:]) > 0:
            if sum(self.x[3:]) > 0:
                raise ValueError("4")
            # General cubic formula https://en.wikipedia.org/wiki/Cubic_equation#General_cubic_formula
            self.delt = set()
            self.delt.add((self.x[1]**2)+(-3*self.x[2]*self.x[0]))
            self.delt.add((2*(self.x[1]**3))+(-9*self.x[2]*self.x[1]*self.x[0])+(27*(self.x[2]**2)*self.a))
        elif self.x[1] > 0:
            self.delt = (self.x[0]**2)+(-4*self.x[1]*self.a)
        else:
            self.delt = None
    def pierwiastek(self):
        self.delta()
        try:
            pierdel = math.sqrt(self.delt)
        except:
            pierdel = "ujemna wyszła"
        return pierdel
    def miejsca0(self):
        self.delta()
        if sum(self.x[2:]) > 0:
            if sum(self.x[3:]) > 0:
                raise ValueError("4")
        try:
            if self.delt == None:
                self.sol.add(-self.a/self.x[0])
                pass
            if self.delt > 0 and self.x[1] != 0:
                self.sol.add((-1*self.x[0]+self.delt)/(2*self.x[1]))
                self.sol.add((-1*self.x[0]-self.delt)/(2*self.x[1]))
        except:
            pass
    def new(liczba):
        end = []
        st = ""
        for i in liczba:
            if liczba[0] == i:
                st += i
            elif i == "+":
                end.append(st)
                st = ""
            elif i == "-":
                end.append(st)
                st = i
            else:
                st += i
        if end[-1] != st:
            end.append(st)
        nonx = []
        x = [[] for _ in range(10000)]
        for i in end:
            cur = ""
            sas = ""
            for j in i:
                if j == "x":
                    cur += j
                elif cur == "x":
                    sas += j
            if cur == "":
                nonx.append(i)
            else:
                try:
                    x[int(sas)-1].append(i)
                except:
                    x[0].append(i)
        ennonx = [int(i) for i in nonx]
        a = sum(ennonx)
        enx = [sum([int(j.replace(f"x{en+1 if en+1 > 1 else ''}", "") if j[0] != "x" else 1) for j in i]) for en, i in enumerate(x)]
        return funkcja(a, enx)

if __name__ == "__main__":
    print("Daj funkcje chuju: ")
    a = input()
    fun = funkcja.new(a)
    print(fun.print())
    print(fun.sol)
    print(fun.delt)
    try:
        print(fun.p)
        print(fun.q)
    except:
        pass
