#!/bin/bash
format="%Y-%m-%d"
ost=$(date -r ~/Dokumenty/dni +"${format}")
td=$(date +"${format}")
dni=$(cat ~/Dokumenty/dni)
help() {
	cat << EOF
-r Reset
-h Help
-p (arg) dni + arg
-m (arg) dni - arg
-i info o dniach
-t info na telefon
else dni + 1
EOF
}
info() {
	cat << EOF
${by}
Ostatni zapis: ${ost}
Dzisiejszy dzień: ${td}
Ostatni dzień: ${dni}
Następny dzień: $((${dni}+1))
EOF
}
if [ $ost == $td ]; then
	by="Były dni skurwielu ${dni}"
else
	by="Nie było dni skurwielu Teraz:$((${dni}+1))"
fi
while getopts rhp:m:itb flag
do
	case "${flag}" in
		h) help && exit;;
		r) echo 0 &> ~/Dokumenty/dni && echo "zresetowano dni" && exit;;
		p) dni=$((${dni}+${OPTARG})) && echo "Zapisano dzień ${dni}" && echo ${dni} &> ~/Dokumenty/dni && exit;;
		m) dni=$((${dni}-${OPTARG})) && echo "Zapisano dzień ${dni}" && echo ${dni} &> ~/Dokumenty/dni && exit;;
		i) info && exit;;
		t) kdeconnect-cli -d $(kdeconnect-cli -l --id-only) --ping-msg "${by}" && exit;;
		b) echo ${by} && echo ${by} && echo ${by} && echo ${by} && exit;;
	esac
done
dni=$((${dni}+1))
echo "Zapisano dzień ${dni}"
echo ${dni} &> ~/Dokumenty/dni
