#!/usr/bin/env python3
import yaml, argparse, random, wonderwords, datetime, string
from dateutil.relativedelta import relativedelta
from pathlib import Path
def translate(word, side = "braill") -> str:
    if side == "braill":
        braill = {"a": "⠁","b": "⠃","c": "⠉","d": "⠙","e": "⠑","f": "⠋","g": "⠛","h": "⠓","i": "⠊","j": "⠚","k": "⠅","l": "⠇","m": "⠍","n": "⠝","o": "⠕","p": "⠏","q": "⠟","r": "⠗","s": "⠎","t": "⠞","u": "⠥","v": "⠧","w": "⠺","x": "⠭","y": "⠽","z": "⠵","ą":"⠡","ć":"⠩","ę":"⠱","ł":"⠣","ń":"⠹","ó":"⠬","ś":"⠪","ż":"⠯","ź":"⠮","0":"⠼⠚","1":"⠼⠁","2":"⠼⠃","3":"⠼⠉","4":"⠼⠙","5":"⠼⠑","6":"⠼⠋","7":"⠼⠛","8":"⠼⠓","9":"⠼⠊"}
        return ''.join(braill.get(ch,ch) for ch in word)
    if side == "normal":
        normal = {"⠁":"a","⠃":"b","⠉":"c","⠙":"d","⠑":"e","⠋":"f","⠛":"g","⠓":"h","⠊":"i","⠚":"j","⠅":"k","⠇":"l","⠍":"m","⠝":"n","⠕":"o","⠏":"p","⠟":"q","⠗":"r","⠎":"s","⠞":"t","⠥":"u","⠧":"v","⠺":"w","⠭":"x","⠽":"y","⠵":"z","⠡":"ą","⠩":"ć","⠱":"ę","⠣":"ł","⠹":"ń","⠬":"ó","⠪":"ś","⠯":"ż","⠮":"ź"}
        word = word.replace("⠼⠚", "0").replace("⠼⠁", "1").replace("⠼⠃", "2").replace("⠼⠉", "3").replace("⠼⠙", "4").replace("⠼⠑", "5").replace("⠼⠋", "6").replace("⠼⠛", "7").replace("⠼⠓", "8").replace("⠼⠊", "9")
        return ''.join(normal.get(ch,ch) for ch in word)
def qchoice() -> None:
    wor = w.word()
    print(f"{translate(wor)} means")
    wors = w.random_words(4, word_min_length=len(wor), word_max_length=len(wor))
    wors[random.randint(0,3)] = wor
    wo = [f"{wors.index(wo)+1} {wo}" for wo in wors] 
    print('\n'.join(wo))
    try:
        ans = input("Which one: ")
    except KeyboardInterrupt:
        exit()
    anin = True
    try:
        ans = int(ans)
    except:
        anin = False
    if ans == wor:
        print("Great")
    elif anin and wor == wors[ans-1]:
        print("Great")
    else:
        print(f"Correct answer is {wor}")
        raise ValueError("Braille or you'll stay blank")
def qchar() -> None:
    le = random.choice(string.ascii_lowercase)
    print(f"{translate(le)} is")
    les = [random.choice(string.ascii_lowercase) for i in range(4)]
    les[random.randint(0,3)] = le
    woles = [f"{les.index(lo)+1} {lo}" for lo in les]
    print('\n'.join(woles))
    try:
        ans = input("Which one: ").lower()
    except KeyboardInterrupt:
        exit()
    anin = True
    try:
        ans = int(ans)
    except:
        anin = False
    if ans == le:
        print("Great")
    elif anin and le == les[ans-1]:
        print("Great")
    else:
        print(f"Correct asnwer is {le}")
        raise ValueError("Braille or you'll stay blank")
def menu() -> None:
    print("\033cWelcome to duolingo for blind")
    print(f"Your current streak: {streak}")
    options = ["Play", "Options", "Exit"]
    opts = [f"{options.index(op)+1} {op}" for op in options]
    print("\n".join(opts))
    try:
        opt = input("Which to play: ").lower()
    except KeyboardInterrupt:
        exit()
    if opt in ["play", "p", "1"]:
        play()
    if opt in ["options", "o", "2"]:
        pass
    if opt in ["exit", "e", ":q", "3"]:
        exit()
def play() -> None:
    playmodes = ["char", "choice"]
    if lives =< 0:
        print("You don't have lives")
    else:
        for i in range(lessonLength):
            if lives > 0:
                try:
                    play = random.choice(playmodes)
                    if play == "char":
                        qchar()
                    elif play == "choice":
                        qchoice()
                except Exception as e:
                    print(e)
            else:
                print("Your lives are gone")
        print("Congrats you compleat a lesson")
def main() -> None:
    global w, streak, lives, lessonLength
    time = datetime.datetime.now()
    try:
        with open(f"{Path.home()}/.config/duo.yaml", "r+") as f:
            conf = yaml.load(f, Loader=yaml.FullLoader)
    except:
        with open(f"{Path.home()}/.config/duo.yaml", "w+") as f:
            conf = {"streak": {"count": 0, "data": time.strftime("%d.%m.%Y")}, "lives": 5, "length": 5}
            yaml.dump(conf, f)
    streak = conf["streak"]["count"]
    sdata = conf["streak"]["data"]
    lives = conf["lives"]
    lessonLength = conf["length"]
    w = wonderwords.RandomWord()
    menu()

if __name__ == "__main__":
    main()
