#!/usr/bin/env python3
import math
import sys
sys.set_int_max_str_digits(99999999)
def wzór(n, x, y, z):
    return (math.factorial(n)*x)+(math.factorial(z)//math.factorial(z-y))
print('n = total numbers')
print('z = number of options - y')
print('x = missing spots')
print('y = options that cannont be in in x')
n = int(input("n: "))
z = int(input("z: "))
x = int(input("x: "))
y = int(input("y: "))
print(wzór(n, x, y, z))
