#!/usr/bin/env python3
import os, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-i", "--illuminati", help="From Illuminati?", action=argparse.BooleanOptionalAction)
parser.add_argument("-s", "--single", help="single")
args = parser.parse_args()
illuminati = {"a":"ꚛ","b":"✡","c":"⌜","d":"↧","e":"⌟","f":"♂","g":"]","h":".","i":"+","j":"Δ","k":"☿","l":"⌞","m":"󰗧","n":"H","o":"T","p":":","q":"┴","r":"X","s":"◇","t":"⸷","u":"⸶","v":"♃","w":"⌧","x":"⼟","y":"󰇙","z":"𝒩","0":"⁞","1":"⸪","2":"⯊","3":"⯋","4":"□-□","5":"Ᏸ","6":"✀↑","7":"✀↓","8":"✀→","9":"✀←",",":"ᛞ",";":"𝟑",":":"𝟑̡",".":"𝟔","!":"𝟗","?":"𝟼𝟿"}
normal = {"ꚛ":"a","✡":"b","⌜":"c","↧":"d","⌟":"e","♂":"f","]":"g",".":"h","+":"i","δ":"j","☿":"k","⌞":"l","󰗧":"m","h":"n","t":"o",":":"p","┴":"q","x":"r","◇":"s","⸷":"t","⸶":"u","♃":"v","⌧":"w","⼟":"x","󰇙":"y","𝒩":"z","⁞":"0","⸪":"1","⯊":"2","⯋":"3","Ᏸ":"5","ᛞ":",","𝟑":";","𝟑̡":":","𝟔":".","𝟗":"!"}

while not args.illuminati and args.single == None:
    print("\x1b[38;2;203;166;247m\x1b[0m\x1b[48;2;203;166;247m\x1b[38;2;24;24;37mYou\x1b[0m\x1b[38;2;203;166;247m\x1b[0m")
    try:
        a = input().replace('"', '').lower()
    except:
        break
    if a in ["exit",":q"]:
        break
    print("")
    print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mIlluminati\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
    print(''.join(illuminati.get(ch,ch) for ch in a))
    print("")
    print("\x1b[91;1m———————————————————————\x1b[0m")
    print("")
while args.illuminati and args.single == None:
    print("\x1b[38;2;203;166;247m\x1b[0m\x1b[48;2;203;166;247m\x1b[38;2;24;24;37mYou\x1b[0m\x1b[38;2;203;166;247m\x1b[0m")
    try:
        a = input().replace('"', '').lower()
    except:
        break
    if a in ["exit",":q"]:
        break
    print("")
    print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mAntyIlluminati\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
    a = a.replace("𝟼𝟿","?").replace("□-□","4").replace("✀↑","6").replace("✀↓","7").replace("✀→","8").replace("✀←","9")
    print(''.join(normal.get(ch,ch) for ch in a))
    print("")
    print("\x1b[91;1m———————————————————————\x1b[0m")
    print("")
if args.single != None:
    if not args.illuminati:
        print(''.join(illuminati.get(ch,ch) for ch in args.single.lower()))
    elif args.enchant:
        a = args.single.lower().replace("𝟼𝟿","?").replace("□-□","4").replace("✀↑","6").replace("✀↓","7").replace("✀→","8").replace("✀←","9")
        print(''.join(normal.get(ch,ch) for ch in a))
