#!/bin/bash
tgpt -q "opowiedz mi żart o graczu league of legends" &> "/home/wilwe/Dokumenty/aiout"
cat /home/wilwe/Dokumenty/aiout
playerctl pause
spd-say -w "$(cat /home/wilwe/Dokumenty/aiout)"
playerctl play
