#!/usr/bin/env python3
import os, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-m", "--morse", help="From morse?", action=argparse.BooleanOptionalAction)
parser.add_argument("-s", "--single", help="single")
args = parser.parse_args()
morse = {"a":".- ","b":"-... ","c":"-.-. ","d":"-.. ","e":". ","f":"..-. ","g":"--. ","h":".... ","i":".. ","j":".--- ","k":"-.- ","l":".-.. ","m":"-- ","n":"-. ","o":"--- ","p":".--. ","q":"--.- ","r":".-. ","s":"... ","t":"- ","u":"..- ","v":"...- ","w":".-- ","x":"-..- ","y":"-.-- ","z":"--.. ","ą":".-.- ","ć":"-.-.. ","ę":"..-.. ","ł":".-..- ","ń":"--.-- ","ó":"---. ","ś":"...-... ","ż":"--..- ","ź":"--..-. ","0":"----- ","1":".----⠁ ","2":"..--- ","3":"...-- ","4":"....- ","5":"..... ","6":"-.... ","7":"--... ","8":"---.. ","9":"----.","?": "..--.."," ":"/ "}
normal = {".-":"a","-...":"b","-.-.":"c","-..":"d",".":"e","..-.":"f","--.":"g","....":"h","..":"i",".---":"j","-.-":"k",".-..":"l","--":"m","-.":"n","---":"o",".--.":"p","--.-":"q",".-.":"r","...":"s","-":"t","..-":"u","...-":"v",".--":"w","-..-":"x","-.--":"y","--..":"z",".-.-":"ą","-.-..":"ć","..-..":"ę",".-..-":"ł","--.--":"ń","---.":"ó","...-...":"ś","--..-":"ż","--..-.":"ź","-----":"0",".----⠁":"1","..---":"2","...--⠉":"3","....-":"4",".....":"5","-....":"6","--...":"7","---..":"8","----.":"9","/":" ",",/":", ","./":". ","!/":"! ","..--..":"?"}

while not args.morse and args.single == None:
    print("\x1b[38;2;203;166;247m\x1b[0m\x1b[48;2;203;166;247m\x1b[38;2;24;24;37mYou\x1b[0m\x1b[38;2;203;166;247m\x1b[0m")
    try:
        a = input().replace('"', '').lower()
    except:
        break
    if a in ["exit",":q"]:
        break
    print("")
    print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mMorse\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
    print(''.join(morse.get(ch,ch) for ch in a))
    print("")
    print("\x1b[91;1m———————————————————————\x1b[0m")
    print("")
while args.morse and args.single == None:
    print("\x1b[38;2;203;166;247m\x1b[0m\x1b[48;2;203;166;247m\x1b[38;2;24;24;37mYou\x1b[0m\x1b[38;2;203;166;247m\x1b[0m")
    try:
        a = input().replace('"', '').lower()
    except:
        break
    if a in ["exit",":q"]:
        break
    print("")
    print("\x1b[38;2;166;227;161m\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mUnMorse\x1b[0m\x1b[38;2;166;227;161m\x1b[0m")
    print(''.join(normal.get(word,word) for word in a.split()))
    print("")
    print("\x1b[91;1m———————————————————————\x1b[0m")
    print("")
if args.single != None:
    if not args.morse:
        print(''.join(morse.get(ch,ch) for ch in args.single.lower()))
    elif args.morse:
        print(''.join(normal.get(word,word) for word in args.single.lower().split()))
