#!/usr/bin/env python3
import pygame
import time
import random

pygame.init()

height = 800
weight = 800
screen = pygame.display.set_mode((height,weight))
class yellow():
    def __init__(self, x, y, r, speed):
        self.x = x
        self.y = y
        self.r = r
        self.modx = 0
        self.mody = 0
        self.speed = speed
        self.move = True
    def draw(self):
        pygame.draw.circle(screen, (255,255,0), (self.x,self.y),self.r)
        

pygame.display.set_caption("Particle")

pa = yellow(200, 200, 10,0.1)
pe = yellow(200, 100, 15,0.2)
particles = [pa, pe]

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN:
            match event.key:
                case pygame.K_LEFT:
                    pa.modx -=pa.speed
                case pygame.K_RIGHT:
                    pa.modx +=pa.speed
                case pygame.K_UP:
                    pe.mody -=pe.speed
                case pygame.K_DOWN:
                    pe.mody +=pe.speed
                case _:
                    pass
        if event.type == pygame.KEYUP:
            if event.key == pygame.K_LEFT or event.key == pygame.K_RIGHT:
                pa.modx = 0
            elif event.key == pygame.K_UP or event.key == pygame.K_DOWN:
                pe.mody = 0
    screen.fill((0,0,0))
    if int(pa.x+pa.modx) < 0:
        pa.x = 0
    elif int(pa.x+pa.modx) > weight:
        pa.x = weight
    if int(pe.y+pe.mody) < 0:
        pe.y = 0
    elif int(pe.y+pe.mody) > height:
        pe.y = height
    pa.x += pa.modx
    pe.y += pe.mody
    for particle in particles:
        particle.draw()
    pygame.display.update()
