#!/bin/bash
tgpt --provider phind -q "opowiedz mi żart polityczny chuj mnie obchodzi kto gdzie i jak" &> "/home/wilwe/Dokumenty/aiout"
cat /home/wilwe/Dokumenty/aiout
playerctl pause
spd-say -w "$(cat /home/wilwe/Dokumenty/aiout)"
playerctl play
