#!/usr/bin/env python
import random, string, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-l", "--length", help="set length", default=5, type=int)
args = parser.parse_args()
x = ""
for b in range(args.length):
    x += random.choice(string.ascii_letters)
print(x)
