#!/usr/bin/env python3
import random
print("\033c")
yes = ['yes', 'y', 'tak', 't']
red = [1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]
green = [0]
black = [2,4,6,8,10,11,13,15,17,20,22,24,26,28,29,31,33,35]
odd = [2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36]
even = [1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35]
st12 = [1,2,3,4,5,6,7,8,9,10,11,12]
nd12 = [13,14,15,16,17,18,19,20,21,22,23,24]
rd12 = [25,26,27,28,29,30,31,32,33,34,35,36]
stLine = [1,4,7,10,13,16,19,22,25,28,31,34]
ndLine = [2,5,8,11,14,17,20,23,26,29,32,35]
rdLine = [3,6,9,12,15,18,21,22,27,30,33,36]
low = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
hi = [19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]
chujnia = green + low + hi + ["red", "green", "black", "odd", "even", "st12", "nd12", "rd12" "stLine", "ndLine", "rdLine", "low", "hi"]
def help():
    print("\033c")
    print("0-36")
    print("red "+str(red))
    print("black "+str(black))
    print("odd "+str(odd))
    print("even "+str(even))
    print("1st12 "+str(st12))
    print("2nd12 "+str(nd12))
    print("3rd12 "+str(rd12))
    print("1stLine "+str(stLine))
    print("2ndLine "+str(ndLine))
    print("3rdLine "+str(rdLine))
    print("low "+str(low))
    print("hi "+str(hi))
def cont():
    print("Continue?")
    global a
    F = input("")
    match F.lower():
        case R if R in yes:
            get_value()
            main()
        case R if R in chujnia:
            a = F.lower()
            main()
def get_value():
    global a
    a = str(input("Na co obstawiasz: "))
    return a
def main():
	los = int(random.randrange(0,37))
	match a.lower():
	    case "odd" if los in odd:
	        print("Wygrałeś")
	    case "red" if los in red:
	        print("Wygrałeś")
	    case "black" if los in black:
	        print("Wygrałeś")
	    case "even" if los in even:
	        print("Wygrałeś")
	    case "st12" if los in st12:
	        print("Wygrałeś")
	    case "nd12" if los in nd12:
	        print("Wygrałeś")
	    case "rd12" if los in rd12:
	        print("Wygrałeś")
	    case "stline" if los in stLine:
	        print("Wygrałeś")
	    case "ndline" if los in ndLine:
	        print("Wygrałeś")
	    case "rdline" if los in rdLine:
	        print("Wygrałeś")
	    case "hi" if los in hi:
	        print("Wygrałeś")
	    case "low" if los in low:
	        print("Wygrałeś")
	    case chu if chu in str(los):
	        print("Wygrałeś")
	    case "help":
	        help()
	    case _:
	        print("przegrałeś")
	if a.lower() != "help":
	    if los in red:
	        print(f"Czerwony {str(los)}")
	    if los in green:
	        print(f"Zielony {str(los)}")
	    if los in black:
	        print(f"Czarny {str(los)}")
	cont()
	
help()
get_value()
main()
