#!/usr/bin/env python3
import random
print("\033c")
yes = ['yes', 'y', 'tak', 't', '']
end = ['no', 'n', ':q', 'nie']
red = [1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]
green = [0]
black = [2,4,6,8,10,11,13,15,17,20,22,24,26,28,29,31,33,35]
odd = [x for x in range(38) if x % 2 == 0]
even = [x for x in range(38) if x % 2 != 0]
st12 = [x+1 for x in range(12)]
nd12 = [x+13 for x in range(12)]
rd12 = [x+25 for x in range(12)]
stLine = [x for x in range(37) if x % 3 == 1]
ndLine = [x+1 for x in range(37) if x % 3 == 1]
rdLine = [x+2 for x in range(37) if x % 3 == 1]
low = [x+1 for x in range(18)]
hi = [x for x in range(37) if x >= 19]
chujnia = green + low + hi + ["red", "green", "black", "odd", "even", "st12", "nd12", "rd12" "stLine", "ndLine", "rdLine", "low", "hi"]
def help():
    print("\033c")
    print("0-36")
    print("red "+str(red))
    print("black "+str(black))
    print("odd "+str(odd))
    print("even "+str(even))
    print("1st12 "+str(st12))
    print("2nd12 "+str(nd12))
    print("3rd12 "+str(rd12))
    print("1stLine "+str(stLine))
    print("2ndLine "+str(ndLine))
    print("3rdLine "+str(rdLine))
    print("low "+str(low))
    print("hi "+str(hi))
def cont():
    print("Continue?")
    global a
    try:
        F = input("")
    except:
        F = ":q"
    match F.lower():
        case R if R in end:
            print("")
        case R if R in yes:
            main()
        case R if R in chujnia:
            a = F.lower()
            main()
def get_value():
    global a
    try:
        a = str(input("Na co obstawiasz: "))
    except:
        a = None
        return a
    return a
def main():
    if a == None:
        return
    los = int(random.randrange(0,37))
    match a.lower():
        case "odd" if los in odd:
            print("Wygrałeś")
        case "red" if los in red:
            print("Wygrałeś")
        case "black" if los in black:
            print("Wygrałeś")
        case "even" if los in even:
            print("Wygrałeś")
        case "st12" if los in st12:
            print("Wygrałeś")
        case "nd12" if los in nd12:
            print("Wygrałeś")
        case "rd12" if los in rd12:
            print("Wygrałeś")
        case "stline" if los in stLine:
            print("Wygrałeś")
        case "ndline" if los in ndLine:
            print("Wygrałeś")
        case "rdline" if los in rdLine:
            print("Wygrałeś")
        case "hi" if los in hi:
            print("Wygrałeś")
        case "low" if los in low:
            print("Wygrałeś")
        case chu if chu in str(los):
            print("Wygrałeś")
        case "help":
            help()
        case _:
            print("przegrałeś")
    if a.lower() != "help":
        if los in red:
            print(f"Czerwony {str(los)}")
        if los in green:
            print(f"Zielony {str(los)}")
        if los in black:
            print(f"Czarny {str(los)}")
    cont()
	
help()
get_value()
main()
