#!/bin/bash
rx1=$(cat /sys/class/net/enp2s0/statistics/rx_bytes)
while sleep 1; do
    rx2=$(cat /sys/class/net/enp2s0/statistics/rx_bytes)
    printf 'Download rate: %s B/s\n' "$((rx2-rx1))"
    rx1=$rx2
done
