#!/bin/bash
x=("0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "A" "B" "C" "D" "E" "F")
y=("8" "9" "A")
z=("0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "A")
for s in ${y[*]}
do
	if [ $s != 'A' ]; then
		for u in ${x[*]}
		do
			for k in ${x[*]}
			do
				echo -e "U+1d${s}${u}${k} \U1d${s}${u}${k}"
			done
		done
	else
		for u in ${z[*]}
		do
			for k in ${x[*]}
			do
				echo -e "U+1d${s}${u}${k} \U1d${s}${u}${k}"
			done
		done
	fi
done
