#!/usr/bin/env python3
import os, argparse
parser = argparse.ArgumentParser()
parser.add_argument("-c", "--spc", help="From spc?", action=argparse.BooleanOptionalAction)
parser.add_argument("-s", "--single", help="single")
args = parser.parse_args()
spc = {"a":"110","b":"320","c":"530","d":"740","e":"950","f":"1160","g":"1370","h":"1580","i":"1790","j":"1910","k":"2120","l":"2330","m":"2540","n":"2750","o":"2960","p":"3170","q":"3380","r":"3590","s":"3710","t":"3920","u":"4130","v":"4340","w":"4550","x":"4760","y":"4970","z":"5180","ą":"210","ć":"630","ę":"1150","ł":"2430","ń":"2850","ó":"3160","ś":"3810","ż":"5280","ź":"5380","0":"620","1":"6210","2":"6320","3":"6430","4":"6540","5":"6650","6":"6760","7":"6870","8":"6980","9":"7190"," ":"0/0","'":"'0","!":"!0",".":".0",",":",0",":":":0","?":"?0","%":"%0","$":"$0"}
normal = {"11":"a","32":"b","53":"c","74":"d","95":"e","116":"f","137":"g","158":"h","179":"i","191":"j","212":"k","233":"l","254":"m","275":"n","296":"o","317":"p","338":"q","359":"r","371":"s","392":"t","413":"u","434":"v","455":"w","476":"x","497":"y","518":"z","21":"ą","63":"ć","115":"ę","243":"ł","285":"ń","316":"ó","381":"ś","528":"ż","538":"ź","62":"","621":"1","632":"2","643":"3","654":"4","665":"5","676":"6","687":"7","698":"8","719":"9","/":" "}

while not args.spc and args.single == None:
    print("\x1b[38;2;203;166;247m🭃\x1b[0m\x1b[48;2;203;166;247m\x1b[38;2;24;24;37mYou\x1b[0m\x1b[38;2;203;166;247m🭟\x1b[0m")
    try:
        a = input().replace('"', '').lower()
    except:
        break
    if a in ["exit",":q"]:
        break
    print("")
    print("\x1b[38;2;166;227;161m🭃\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mSpc\x1b[0m\x1b[38;2;166;227;161m🭟\x1b[0m")
    print(''.join(spc.get(ch,ch) for ch in a))
    print("")
    print("\x1b[91;1m———————————————————————\x1b[0m")
    print("")
while args.spc and args.single == None:
    print("\x1b[38;2;203;166;247m🭃\x1b[0m\x1b[48;2;203;166;247m\x1b[38;2;24;24;37mYou\x1b[0m\x1b[38;2;203;166;247m🭟\x1b[0m")
    try:
        a = input().replace('"', '').lower()
    except:
        break
    if a in ["exit",":q"]:
        break
    print("")
    print("\x1b[38;2;166;227;161m🭃\x1b[0m\x1b[48;2;166;227;161m\x1b[38;2;24;24;37mUnSpc\x1b[0m\x1b[38;2;166;227;161m🭟\x1b[0m")
    print(''.join(normal.get(word,word) for word in a.replace('0'," ").split()))
    print("")
    print("\x1b[91;1m———————————————————————\x1b[0m")
    print("")
if args.single != None:
    if not args.spc:
        print(''.join(spc.get(ch,ch) for ch in args.single.lower()))
    elif args.spc:
        print(''.join(normal.get(word,word) for word in args.single.lower().replace('0'," ").split()))
