#!/usr/bin/env python3
import random
value = 0
symbols = ['󱀝', '♡', '󰣎', '󰣑']
cards = ["2","3","4","5","6","7","8","9","1","J","Q","K","A"]
asc = 0
handc = []
def as_update():
    global asc
    global value
    while value > 21 and asc > 0:
        value = value-9
        asc = asc-1
def count_val():
    global value
    global asc
    for i in hand:
        if i == "1":
            value = value + 10
        elif i.isnumeric():
            value = value + int(i)
        elif i == "J":
            value = value + 10
        elif i == "Q":
            value = value + 10
        elif i == "K":
            value = value + 10
        elif i == "A":
            asc = asc +1
            value = value + 10
        as_update()
def draw():
    global hand
    hand = hand + cards[random.randint(0,12)]
def get_hand():
    global handc
    for i in hand:
        if i == "1":
            handc = handc + ["10"]
        else:
            handc = handc + [i]
hand = cards[random.randint(0,12)] + cards[random.randint(0,12)]
for i in [1,2]:
    draw()
count_val()
get_hand()
print(" ".join(handc))
print(value)
if value > 21:
    print("przegrałeś")
else:
    print("Wygrałeś")
