#!/bin/bash
y=("030" "031" "032" "033" "034" "035" "036" "1AB" "1AC" "1DC" "1DD" "1DE" "1DF" "20D" "20E" "FE2")
x=("0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "A" "B" "C" "D" "E" "F")
for s in ${y[*]}
do
	for z in ${x[*]}
	do
		echo -e "U+${s}${z} A\U${s}${z}"
	done
done
echo -e "U+20F0 A\U20F0"
