#!/bin/bash
trans -t ru -j -o $HOME/Dokumenty/trans -brief -show-original n -show-translation Y -show-original-phonetics n -show-translation-phonetics n -show-languages n -show-dictionary n -show-alternatives n -no-ansi -no-bidi -no-autocorrect "$1"
cat $HOME/Dokumenty/trans
spd-say -l RU -w "$(cat $HOME/Dokumenty/trans)"
