#!/usr/bin/env python3
import os
def read_items(file_path):
    with open(file_path, 'r') as file:
        items = [line.strip() for line in file]
    return items
file = str(input('jaki plik wariacie: '))
print ('\033[1A\033[K\033[1A')
items = read_items(file)
s = '\033[101m| S |\033[0m'
a = '\033[41m| A |\033[0m'
b = '\033[43m| B |\033[0m'
c = '\033[103m| C |\033[0m'
d = '\033[42m| D |\033[0m'
f = '\033[102m| F |\033[0m'
print ("\033[31m---------------------------------------------\033[0m")
print (s)
print ("\033[31m---------------------------------------------\033[0m")
print (a)
print ("\033[31m---------------------------------------------\033[0m")
print (b)
print ("\033[31m---------------------------------------------\033[0m")
print (c)
print ("\033[31m---------------------------------------------\033[0m")
print (d)
print ("\033[31m---------------------------------------------\033[0m")
print (f)
print ("\033[31m---------------------------------------------\033[0m")
for i in items:
    print (i)
    x = str(input('Tier: '))
    if x == 's':
        s = s + ' ' + i + " |"
        print ('\033[14A' + s + '\033[13B')
    if x == 'a':
        a = a + ' ' + i + " |"
        print ('\033[12A' + a + '\033[11B')
    if x == 'b':
        b = b + ' ' + i + " |"
        print ('\033[10A' + b + '\033[9B')
    if x == 'c':
        c = c + ' ' + i + " |"
        print ('\033[8A' + c + '\033[7B')
    if x == 'd':
        d = d + ' ' + i + " |"
        print ('\033[6A' + d + '\033[5B')
    if x == 'f':
        f = f + ' ' + i + " |"
        print ('\033[4A' + f + '\033[3B')
    print ('\033[1A\033[K\033[1A\033[K\033[1A')
    
