#!/usr/bin/env python3
import sys, os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    print(file, f, ext)
    sss = music_tag.load_file(file)
    title = str(sss["tracknumber"])
    nt = f"{title:0>2}{f}{ext}"
    mv = subprocess.Popen(["mv", file, nt])
    mv.wait()

