#!/usr/bin/env python3
import sys, os, subprocess, music_tag
import time
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    sss = music_tag.load_file(file)
    title = str(sss.get_tag("title"))
    nt = file[file.find(title):]
    mv = subprocess.Popen(["mv", file, nt])
    mv.wait()

