#!/usr/bin/env python
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    sss = music_tag.load_file(file)
    sss.remove_tag('albumartist')
    sss.save()
