#!/usr/bin/env python
import os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
alb = subprocess.check_output(['zenity', '--entry', f'--text=Album name']).decode("utf-8").replace('\n', '')

for file in files:
    sss = music_tag.load_file(file)
    sss.remove_tag('album')
    sss.append_tag('track')
    sss.append_tag('totaltracks')
    sss.save()
