#!/usr/bin/env python3
import sys, os, subprocess
from pathvalidate import sanitize_filepath
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    subprocess.Popen(["ffmpeg", "-y", "-i", file, "-vn", "-c:a", "copy", "tmp."+ext]).wait()
    subprocess.Popen(["mv", "-f", "tmp." + ext, file]).wait()
