#!/bin/bash
x=$(echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)
trans -t es -j -o $HOME/Dokumenty/trans -show-original n -show-translation Y -show-original-phonetics n -show-translation-phonetics n -show-languages n -show-dictionary n -show-alternatives n -no-ansi -no-bidi -brief -i "$x"
spd-say -l ES -w "$(cat $HOME/Dokumenty/trans)"
