#!/bin/bash
x=$(echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)
trans -t ru -j -brief -o $HOME/Dokumenty/trans -show-original n -show-translation Y -show-original-phonetics n -show-translation-phonetics n -show-languages n -show-dictionary n -show-alternatives n -no-ansi -no-bidi -i "$x"
spd-say -l RU -w "$(cat $HOME/Dokumenty/trans)"
