#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    subprocess.Popen(["trans", "-t", "ko", "-j", "-brief", "-o", f"{f}_ko{ext}", "-show-original", "n", "-show-translation", "Y", "-show-original-phonetics", "n", "-show-translation-phonetics", "n", "-show-languages", "n", "-show-dictionary", "n", "-show-alternatives", "n", "-no-ansi", "-no-bidi", "-no-autocorrect", "-i", file]).wait()
