#!/bin/bash
bard-cli "Zamień każdą osobę i zaimki słowem 'GRYZAK' "$(cat "$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")")"" &> $HOME/Dokumenty/aiout
x="$(cat "$HOME/Dokumenty/aiout")"
echo "${x//GRYZAK/"chuj nie myty"}" &> $HOME/Dokumenty/aiout
spd-say -w "$(cat "$HOME/Dokumenty/aiout")"
