#!/bin/bash
bard-cli "Zamień każdą osobę i zaimki słowem GRYZAK "$(cat "$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")")"" &> $HOME/Dokumenty/aiout
notify-send "koniec chuju" -a "Ai chuj"
spd-say -w "$(cat '/home/wilwe/Dokumenty/aiout')"
