#!/bin/bash
x=$(bard-cli "Zamień każdą osobę i zaimki słowem 'GRYZAK' "$(cat "$(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")")"")
echo "${x//GRYZAK/"Pingwin Spawacz"}" > $HOME/Dokumenty/aiout
spd-say -w "$(cat "$HOME/Dokumenty/aiout")"
