#!/bin/bash
bard-cli "połącz teksty aby były spójne ze sobą $(cat $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)" &> /home/wilwe/Dokumenty/aiout
notify-send "koniec chuju" -a "Ai chuj"
spd-say -w "$(cat '/home/wilwe/Dokumenty/aiout')"
