#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
command = ["kitty", "--hold", "convert"]
for file in files:
    command.append(file)
command.append("output.gif")
subprocess.Popen(command).wait()
