#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    ffp = subprocess.Popen(["ffmpeg", "-i", file, "-map", "0:a:0", "-b:a", "24k", f"{file}_24k.mp3"])
    ffp.wait()

