#!/usr/bin/env python3
import sys, os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

audio = subprocess.check_output(["zenity", "--entry", "--text=audio compression"]).decode("UTF-8").replace("\n", '')
for file in files:
    ffp = subprocess.Popen(["ffmpeg", "-i", file, "-map", "0:a:0", "-b:a", audio, f"{file}_compress.mp3"])
    ffp.wait()
