#!/bin/bash
echo "Ten skrypt działa tylko na urządzeniach pochodzących z rodziny archów"
# Aktualizacja systemu
echo "Aktualizuje system"
sudo pacman -Syu &> /dev/null

# pytania o ip maske i dns
read -p "Jakie ip wariacie z maską np. 192.168.21.37/24 " ipadd
read -p "Jaki dns wariacie " ipdns
ipconf

# funkcje instalująco konfiguracyjne
ipconf () {
  ip link show
  read -p "Jaki interface " interface
  echo "ustawianie ip"
  ip add $ipadd dev $interface lifetime
  echo "ustawianie dns"
  # Plik resolve trzyma wszystkie DNSy
  sudo echo "$ipdns" > /etc/resolve.conf
}
inginx () {
  echo "Instaluje Nginx"
  sudo pacman -S nginx &> /dev/null
  echo "Tworzenie Folderów kofiguracyjnych w ~/skrypty/nginx"
  # linkowanie ustawień
  mkdir ~/skrypt/nginx
  mkdir ~/skrypt/nginx/config
  sudo ln -rs /var/www ~/skrypt/nginx/www
  sudo ln -rs /etc/nginx/* ~/skrypt/nginx/config/
}
itor () {
  echo "Instaluje Tora"
  sudo pacman -S tor &> /dev/null
  echo "Tworzenie Folderów konfiguracyjnych w ~/skrypty/tor"
  # linkowanie ustawień
  mkdir ~/skrypt/tor/config
}
issh () {
  echo "Instaluje SSH"
  sudo pacman -S openssh &> /dev/null
  echo "Tworzenie Folderów konfiguracyjnych w ~/skrypt/ssh"
  # linkowanie ustawień
  mkdir ~/skrypt/ssh
  ln -rs ~/.ssh/config ~/skrypt/ssh/config
}
igui () {
  echo "Instaluje Hyprland"
  # Bo nie chce mi się robić wyboru
  sudo pacman -S hyprland &> /dev/null
  echo "Instaluje SDDM"
  sudo pacman -S sddm &> /dev/null
  sudo pacman -S kitty &> /dev/null
  # linkowanie ustawień
  echo "Tworzenie Folderów konfiguracyjnych w ~/skrypt/hyprland"
  mkdir ~/skrypt/hyprland
  ln -rs ~/.config/hypr/hyprland.conf ~/skrypt/hyprland/hyprland.conf
  echo "Tworzenie Folderów konfiguracyjnych w ~/skrypt/sddm"
  mkdir ~/skrypt/sddm
  ln -rs /etc/sddm.conf ~/skrypt/sddm
}

# Pytanie użytkownika co chce zainstalować
read -p "Instalować serwer www (nginx) y/n " www
case "$www" in
  y|Y ) inginx ;;
  n|N ) echo "Skipping" ;;
  * ) echo "co ty sobie kurwa gnojku myślisz" ;;
esac

read -p "Instalować serwer Tor y/n " tor
case "$tor" in
  y|Y ) itor ;;
  n|N ) echo "Skipping" ;;
  * ) echo "że co kurwa" ;;
esac

read -p "Instalować serwer ssh y/n " ssh
case "$ssh" in
  y|Y ) issh ;;
  n|N ) echo "Skipping" ;;
  * ) echo "?" ;;
esac

read -p "Instalować gui y/n " gui
case "$gui" in
  y|Y ) igui ;;
  n|N ) echo "Skipping" ;;
  * ) echo "Co próbujesz" ;;
esac
