#!/usr/bin/env python3
import os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    sss = music_tag.load_file(file)
    albtag = str(sss.get('album'))
    sss.set('genre', albtag)
    sss.remove_tag('album')
    sss.save()
