#!/usr/bin/env python3
import os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    sss = music_tag.load_file(file)
    albtag = str(sss.get('title')).split(", ")
    sss.set('title', albtag[0])
    sss.save()
