#!/usr/bin/env python3
import os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
albart = subprocess.check_output(['zenity', '--entry', f'--text=Album Artist']).decode("utf-8").replace('\n', '').split('|')

for file in files:
    sss = music_tag.load_file(file)
    for ab in albart:
        sss.append_tag('albumartist', ab)
    sss.save()
