#!/usr/bin/env python3
import sys, os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    sss = music_tag.load_file(file)
    fold = file.split("/")[-2]
    art = fold.split(" - ")[0]
    alb = fold.split(" - ")[1]
    sss.append_tag("album", alb)
    sss.append_tag("albumartist", art)
    sss["tracknumber"] = files.index(file)+1
    sss["totaltracks"] = len(files)
    sss.save()
    ind = str(files.index(file)+1)
    nam = os.path.basename(file)[len(ind):]
    mvs = subprocess.Popen(["mv", "-f", file, nam])
