#!/usr/bin/env python
import sys, os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
alb = subprocess.check_output(['zenity', '--entry', f'--text=Album name']).decode("utf-8").replace('\n', '')
albart = subprocess.check_output(['zenity', '--entry', f'--text=Album artist']).decode("utf-8").replace('\n', '')
albart = albart.split('|')

for file in files:
    sss = music_tag.load_file(file)
    sss.append_tag("album", alb)
    for alar in albart:
        sss.append_tag("albumartist", alar)
    sss["tracknumber"] = files.index(file)+1
    sss["totaltracks"] = len(files)
    sss.save()
    ind = str(files.index(file)+1)
    nam = os.path.basename(file)[len(ind):]
    mvs = subprocess.Popen(["mv", "-f", file, nam])
