#!/usr/bin/env python3
import sys, os, subprocess, music_tag
from pathvalidate import sanitize_filepath
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    n = f.split(" - ")
    sss = music_tag.load_file(file)
    sss.append_tag('title', n[-1])
    sss.append_tag('artist', n[0])
    sss.save()
