#!/usr/bin/env python3
import sys, os, subprocess,json
from pathvalidate import sanitize_filepath
import time
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    n = os.path.basename(file).split(" - ")
    if n[-1].find("(") != -1:
        s = n[-1][:n[-1].find("(")]
        s = s[:s.find(".mp3")]
    else:
        s = n[-1][:n[-1].find(".mp3")]
    print("Author:",n[0])
    print("Title:",s)
    print("File:", n[-1])
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, "-c", "copy", "-metadata", f"artist={n[0]}", "-metadata", f"title={s}", "tmp.mp3"])
    ffm.wait()
    mv = subprocess.Popen(["mv", "tmp.mp3", n[-1]])
    mv.wait()
    rm = subprocess.Popen(["rm", file])
