#!/usr/bin/env python3
import sys, os, subprocess
from pathvalidate import sanitize_filepath
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
f, ext = os.path.splitext(os.path.basename(files[0]))
subprocess.Popen(["ffmpeg", "-y", "-i", files[0], '-i', files[1], "-map", "0", "-map", "1", "-c", "copy", "-disposition:v", "attached_pic", "tmp."+ext]).wait()
subprocess.Popen(["mv", "-f", "tmp."+ext, files[0]]).wait()
