#!/usr/bin/env python3
import sys, os, subprocess
from pathvalidate import sanitize_filepath
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
cov = subprocess.check_output(['zenity', '--file-selection']).decode("utf-8")

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    subprocess.Popen(["ffmpeg", "-y", "-i", file, '-i', sanitize_filepath(cov), "-map", "0", "-map", "1", "-c", "copy", "-disposition:v", "attached_pic", "tmp."+ext]).wait()
    subprocess.Popen(["mv", "-f", "tmp." + ext, file]).wait()

