#!/usr/bin/env python3
import sys, yaml, os, subprocess, pylast, music_tag
from pathlib import Path
def getLastApi():
    global confLast
    try:
        with open(f"{Path.home()}/.config/gener.yaml", "r") as f:
            confLast = yaml.load(f, Loader=yaml.FullLoader)
    except:
        key = subprocess.check_output(["zenity", "--entry", "--text", "last.fm Api Key"]).decode("UTF-8").replace('\n','')
        secret = subprocess.check_output(["zenity", "--entry", "--text", "last.fm Api secret"]).decode("UTF-8").replace('\n','')
        username = subprocess.check_output(["zenity", "--entry", "--text", "last.fm Username"]).decode("UTF-8").replace('\n','')
        password = subprocess.check_output(["zenity", "--password", "--text", "last.fm Password"]).decode("UTF-8").replace('\n','')
        confLast = {"key": key, "secret": secret, "username": username, "password": pylast.md5(password)}
        with open(f"{Path.home()}/.conf/gener.yaml", "w+") as f:
            yaml.dump(confLast, f)
getLastApi()
#files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
files = [sys.argv[1]]
network = pylast.LastFMNetwork(
        api_key=confLast["key"],
        api_secret=confLast["secret"],
        username=confLast["username"],
        password_hash=confLast["password"]
        )

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    sss = music_tag.load_file(file)
    title = str(sss["title"])
    artist = str(sss["artist"])
