#!/usr/bin/env python
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    track = subprocess.check_output(['zenity', '--entry', f"--text=Number {os.path.basename(file)} (X/Y)"]).decode("utf-8").replace('\n', '').split("/")
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, "-c", "copy",  "-metadata", f"track={track[0]}", "-metadata", f"TRACKTOTAL={track[1]}", "tmp.mp3"])
    ffm.wait()
    mvs = subprocess.Popen(["mv", "-f", "tmp.mp3", file])
    mvs.wait()

