#!/usr/bin/env python3
import sys, os, subprocess, music_tag
from pathvalidate import sanitize_filepath
import time
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    n, ext = os.path.splitext(os.path.basename(file))
    sss = music_tag.load_file(file)
    sss.append_tag('title', n)
    sss.save()
