#!/usr/bin/env python3
import os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
tit = subprocess.check_output(['zenity', '--entry', f'--text=Title']).decode("utf-8").replace('\n', '')
tit = tit.split("|")

for file in files:
    sss = music_tag.load_file(file)
    for t in tit:
        sss.append_tag("title", t)
    sss.save()

