#!/usr/bin/env python3
import os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
y = subprocess.check_output(['zenity', '--entry', f'--text=Year']).decode("utf-8").replace('\n', '')

for file in files:
    sss = music_tag.load_file(file)
    sss["year"] = y
    sss.save()

