#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
	ffp = subprocess.Popen(["kitty","ffmpeg", "-i", file, f"{f}.mp4"])
	ffp.wait()
