#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
	ffp = subprocess.Popen(["ffmpeg", "-i", file, f"{file}.mp4"])
	ffp.wait()
