#!/usr/bin/env python3
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
	mag = subprocess.Popen(["convert", file, "-channel", "RGB", "-negate", f"{file}_inverted.jpg"])
	mag.wait()
