#!/usr/bin/env python3
import sys, os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    subprocess.Popen(["kitty", "ffmpeg", "-i", file, "-af", "areverse", f"{f[::-1]}{ext}"]).wait()
    sss = music_tag.load_file(f"{f[::-1]}{ext}")
    sss["title"] = sss["title"][::-1]
    sss["artist"] = sss["artist"][::-1]
    sss["album"] = sss["album"][::-1]
    sss["albumartist"] = sss["albumartist"][::-1]
    total = sss["totaltracks"]+1
    sss["track"] = total - sss["track"]
    sss.save()
