#!/usr/bin/env python3
import sys, os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    subprocess.Popen(["kitty", "ffmpeg", "-i", file, "-af", "areverse", f"{f}_reversed{ext}"]).wait()
