#!/usr/bin/env python3
import sys, os, subprocess, music_tag
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    f, ext = os.path.splitext(os.path.basename(file))
    subprocess.Popen(["kitty", "ffmpeg", "-i", file, "-af", "areverse", f"{f[::-1]}{ext}"]).wait()
    sss = music_tag.load_file(f"{f[::-1]}{ext}")
    sss["title"] = str(sss["title"])[::-1]
    sss["artist"] = str(sss["artist"])[::-1]
    sss["album"] = str(sss["album"])[::-1]
    sss["albumartist"] = str(sss["albumartist"])[::-1]
    num = len(files) - files.index(file)
    sss["tracknumber"] = num 
    sss.save()
