#!/usr/bin/env python3
import os, sys
#files = str(os.environ.get("NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")).splitlines()
files = [sys.argv[1]]

for file in files: 
    with open(file, "r+") as f:
        lines = f.readlines()
        donelist = []
        for line in lines:
            s = line.split("Music", 1)
            if s[-1][0] == "/":
                donelist.append(f"file:///home/wilwe/Muzyka{s[-1]}")
            else:
                donelist.append(f"file:///home/wilwe/Muzyka/{s[-1]}")
    with open(file, "w+") as f:
        f.writelines(donelist)
