#!/usr/bin/env python3
import os, sys
import json
files = str(os.environ.get("NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")).splitlines()
#files = [sys.argv[1]]

for file in files: 
    pathtof = file.split("/")
    pathtof = pathtof[0:len(pathtof)-1]
    pathtof = '/'.join(pathtof)
    with open(file, "r") as f:
        lines = f.readlines()
        end = {}
        for line in lines:
            playlist, path = line.split("|")
            #path = path.split("/")
            #path = "/".join(path[path.index("playlist"):-1]).replace("\n", "")
            try:
                if path not in end[playlist]:
                    end[playlist].append(path)
            except KeyError:
                end[playlist] = [path]
        for key, val in end.items():
            with open(pathtof+"/"+key+".m3u", "w+") as fs:
                fs.write("\n".join(val))
