#!/bin/bash

sqlite3 $(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS") << 'END_SQL'
.once playlist_raw.txt
select pl.name, scheme||'/storage/'||uuid||'/'||path||filename from playlist pl inner join playlistmediarelation plr on playlist_id=id_playlist inner join media on id_media=media_id join folder on folder_id=id_folder INNER JOIN device ON media.device_id = device.id_device order by id_playlist, position;
END_SQL
