#!/usr/bin/env python
import sys, os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
alb = subprocess.check_output(['zenity', '--entry', f'--text=Album name']).decode("utf-8")
albart = subprocess.check_output(['zenity', '--entry', f'--text=Album artist']).decode("utf-8")

for file in files:
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, "-c", "copy", "-metadata", f"album={alb.replace('\n', '')}", "-metadata", f"album_artist={albart}", "-metadata", f"track={files.index(file)+1}", "-metadata", f"TRACKTOTAL={len(files)}", "tmp.mp3"])
    ffm.wait()
    ind = str(files.index(file)+1)
    nam = os.path.basename(file)[len(ind):]
    mvs = subprocess.Popen(["mv", "-f", "tmp.mp3", nam])
    mvs.wait()
    rm = subprocess.Popen(["rm", file])
