#!/usr/bin/env python3
import os, subprocess
from pathvalidate import sanitize_filepath
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
cov = subprocess.check_output(['zenity', '--file-selection']).decode("utf-8")

for file in files:
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, '-i', sanitize_filepath(cov), "-map", "0:0", "-map", "1:0", "-c", "copy", "tmp.mp3"])
    ffm.wait()
    mvs = subprocess.Popen(["mv", "-f", "tmp.mp3", file])
    mvs.wait()

