#!/usr/bin/env python3
import os, subprocess
from pathvalidate import sanitize_filepath
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, "-an", "-c:v", "copy", f"{file}.jpg"])
    ffm.wait()

