#!/usr/bin/env python3
import os, subprocess, sys
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
author = subprocess.check_output(["zenity", "--entry", "--text", "Author"]).decode("utf-8")

for file in files:
    met = subprocess.check_output(['zenity', '--entry', f'--text=Title {os.path.basename(file)}']).decode("utf-8")
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, "-c", "copy", "-metadata", f"artist={author.replace('\n', '')}", "-metadata", f"title={met.replace('\n', '')}", "tmp.mp3"])
    ffm.wait()
    mvs = subprocess.Popen(["mv", "-f", "tmp.mp3", file])
    mvs.wait()
