#!/usr/bin/env python
import os, subprocess
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()
alb = subprocess.check_output(['zenity', '--entry', f'--text=Album name']).decode("utf-8")

for file in files:
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, "-c", "copy", "-metadata", f"album={alb.replace('\n', '')}", "tmp.mp3"])
    ffm.wait()
    mvs = subprocess.Popen(["mv", "-f", "tmp.mp3", file])
    mvs.wait()

