#!/usr/bin/env python3
import sys, os, subprocess,json
from pathvalidate import sanitize_filepath
import time
files = os.environ.get('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS').splitlines()

for file in files:
    art = subprocess.check_output(["ffprobe", "-show_entries", "format_tags=artist", "-of", "json", "-i", file]).decode("utf-8")
    title = subprocess.check_output(["ffprobe", "-show_entries", "format_tags=title", "-of", "json", "-i", file]).decode("utf-8")
    art = json.loads(art)["format"]["tags"]["artist"]
    title = json.loads(title)["format"]["tags"]["title"]
    thumb = subprocess.Popen(["yt-dlp", '-o', file, "--convert-thumbnails", "jpg", "--skip-download", "--write-thumbnail", f"ytsearch1:'{art} {title}'"])
    time.sleep(5)
    ffm = subprocess.Popen(["ffmpeg", "-y", "-i", file, '-i', f"{file}.jpg", "-map", "0:0", "-map", "1:0", "-c", "copy", "tmp.mp3"])
    ffm.wait()
    mvs = subprocess.Popen(["mv", "-f", "tmp.mp3", file])
    mvs.wait()
    rms = subprocess.Popen(["rm", f"{file}.jpg"])
    rms.wait()

